# Generated by Django 2.2.8 on 2019-12-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pedidos', '0003_pedido_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pedido', models.ManyToManyField(to='gestion_pedidos.Articulo')),
                ('cliente', models.ManyToManyField(to='gestion_pedidos.Cliente')),
            ],
        ),
    ]
